In [ ]:
!pip uninstall -y torch torchtext torchvision torchaudio && pip install torch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 --index-url https://download.pytorch.org/whl/cu121
!pip install torchtext --no-cache-dir
!pip install einops -q

Found existing installation: torch 2.9.0+cpu
Uninstalling torch-2.9.0+cpu:
  Successfully uninstalled torch-2.9.0+cpu
Found existing installation: torchvision 0.24.0+cpu
Uninstalling torchvision-0.24.0+cpu:
  Successfully uninstalled torchvision-0.24.0+cpu
Found existing installation: torchaudio 2.9.0+cpu
Uninstalling torchaudio-2.9.0+cpu:
  Successfully uninstalled torchaudio-2.9.0+cpu
Looking in indexes: https://download.pytorch.org/whl/cu121
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 780.9/780.9 MB 1.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 116.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 106.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 95.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 50.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 117.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.6 MB/

In [11]:
import torch
import torch.nn as nn
import math

In [21]:
img_test =  torch.randint(0, 2, (4,1 ,50, 200))
img_test = img_test.float()

In [22]:
print(img_test)

tensor([[[[1., 0., 1.,  ..., 0., 0., 1.],
          [1., 0., 1.,  ..., 1., 0., 0.],
          [1., 0., 1.,  ..., 0., 0., 1.],
          ...,
          [1., 1., 1.,  ..., 0., 1., 0.],
          [1., 0., 1.,  ..., 0., 1., 1.],
          [0., 0., 0.,  ..., 1., 1., 1.]]],


        [[[1., 1., 0.,  ..., 0., 1., 1.],
          [0., 1., 1.,  ..., 1., 1., 0.],
          [0., 0., 0.,  ..., 0., 1., 1.],
          ...,
          [0., 1., 0.,  ..., 1., 1., 1.],
          [0., 1., 0.,  ..., 1., 1., 1.],
          [0., 1., 1.,  ..., 1., 1., 0.]]],


        [[[0., 1., 1.,  ..., 0., 1., 0.],
          [0., 0., 0.,  ..., 0., 1., 0.],
          [1., 0., 1.,  ..., 1., 1., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 1.],
          [1., 0., 0.,  ..., 0., 0., 1.],
          [1., 0., 1.,  ..., 1., 0., 1.]]],


        [[[1., 1., 1.,  ..., 0., 0., 0.],
          [1., 0., 1.,  ..., 0., 0., 0.],
          [0., 1., 0.,  ..., 0., 0., 1.],
          ...,
          [0., 0., 1.,  ..., 0., 1., 1.],
    

In [ ]:
from google.colab import drive
drive.mount("/content/drive/")

Mounted at /content/drive/


In [ ]:
data_set = torch.load("/content/drive/MyDrive/Group Project 2025-2026/training_data.pt")

In [ ]:
img_test1 = data_set['images'][0]
print(img_test1)
img_test1 = img_test1.unsqueeze(0)
print(img_test1.shape)

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]])
torch.Size([1, 1, 64, 128])


In [63]:
class Cnn_layer(nn.Module):
  def __init__(self, input_channel, height, width, embedding_dim ,max_len = 5000 ):
    super().__init__()
    self.feature = nn.Sequential(
        #Block 1
        nn.Conv2d(input_channel, 8, kernel_size=3,stride=1, padding=1),
        nn.BatchNorm2d(8),
        nn.LeakyReLU(),
        nn.MaxPool2d(2),
        nn.Dropout2d(0.2),
        #Block 2
        nn.Conv2d(8, 16, kernel_size=3,stride=1, padding=1),
        nn.BatchNorm2d(16),
        nn.LeakyReLU(),
        nn.MaxPool2d(2),
        nn.Dropout2d(0.2),
        #Block 3
        nn.Conv2d(16, 32, kernel_size=3,stride=1, padding=1),
        nn.BatchNorm2d(32),
        nn.LeakyReLU(),
        nn.MaxPool2d(2),
        nn.Dropout2d(0.2),
        #Block 4
        nn.Conv2d(32, 64, kernel_size=3,stride=1, padding=1),
        nn.BatchNorm2d(64),
        nn.LeakyReLU(),

        nn.Dropout2d(0.2),
        #Block 5
        nn.Conv2d(64, 128, kernel_size=3,stride=1, padding=1),
        nn.BatchNorm2d(128),
        nn.LeakyReLU(),

        nn.Dropout2d(0.2)
    )
    self.projection = nn.Linear(128, embedding_dim)
    self.pos_embed = nn.Parameter(torch.randn(1, max_len, embedding_dim))
  def forward(self,x):
  # B, C, H, W
    x = self.feature(x)
    x = torch.flatten(x, start_dim=2)
    x = x.permute(0,2,1)
    x = self.projection(x)
    seq_len = x.shape[1]
    x = x + self.pos_embed[:, :seq_len, :]

    return x

In [64]:
te = Cnn_layer(1,50,200,256)
x = te.forward(img_test)
print(x.shape)

torch.Size([4, 150, 256])


In [45]:
class MultiheadAttention(nn.Module):
  def __init__(self, embedding_dim, num_head:int=4 , dropout: float = 0) -> None:
     super().__init__()
     self.layer_norm=nn.LayerNorm(embedding_dim)
     self.mha = nn.MultiheadAttention(embed_dim=embedding_dim,
                                      num_heads=num_head,
                                      dropout=dropout,
                                      batch_first=True)
  def forward(self,x):
    x_norm = self.layer_norm(x)
    x_attention,_ = self.mha(query = x_norm,
                           key = x_norm,
                           value = x_norm,
                           need_weights = False)
    return  x + x_attention

In [46]:
class MLP_Block(nn.Module):
  def __init__(self, embedding_dim,mlp_size: int = 1024 ,dropout: float = 0.2) :
     super().__init__()
     self.layer_norm=nn.LayerNorm(embedding_dim)
     self.mlp = nn.Sequential(nn.Linear(embedding_dim,mlp_size),
                              nn.GELU(),
                              nn.Dropout(dropout),
                              nn.Linear(mlp_size,embedding_dim),
                              nn.Dropout(dropout))
  def forward(self,x):
    x_norm = self.layer_norm(x)
    x_mlp = self.mlp(x_norm)
    return x + x_mlp

In [47]:
class TransformerEncoderLayer(nn.Module):
  def __init__(self, embedding_dim, num_head:int=4 , attn_dropout: float = 0 , mlp_size: int =1024 , mlp_dropout: float = 0.2 ):
     super().__init__()
     self.attn = MultiheadAttention(embedding_dim,num_head,attn_dropout)
     self.mlp = MLP_Block(embedding_dim,mlp_size,mlp_dropout)
  def forward(self,x):
    x_attn = self.attn(x)
    x_mlp = self.mlp(x_attn)
    return x_mlp

In [48]:
class TransformerEncoder(nn.Module):
    def __init__(self, embedding_dim, num_layers, num_head=4, attn_dropout=0, mlp_size=1024, mlp_dropout=0.2):
        super().__init__()
        self.layers = nn.ModuleList([
            TransformerEncoderLayer(
                embedding_dim=embedding_dim,
                num_head=num_head,
                mlp_size=mlp_size,
                attn_dropout=attn_dropout,
                mlp_dropout=mlp_dropout
            )
            for _ in range(num_layers)
        ])

    def forward(self, x):
        for layer in self.layers:
            x = layer(x)
        return x

In [65]:
class CvT(nn.Module):
  def __init__(self,  input_channel, height, width, embedding_dim,num_layer ):
     super().__init__()
     self.cnn = Cnn_layer(input_channel, height, width, embedding_dim)

     self.transformer= TransformerEncoder(embedding_dim ,num_layer, num_head=4, attn_dropout=0, mlp_size=1024, mlp_dropout=0.2)
  def forward(self,x):
    out1 = self.cnn(x)
    out2 = self.transformer(out1)
    return out2

In [66]:
cvt = CvT(1,50,200,256,4)
tr= cvt.forward(img_test)
print(tr.shape)
print(tr)

torch.Size([4, 150, 256])
tensor([[[ 1.6198,  0.8193, -1.5546,  ...,  1.6263, -1.0001, -2.0356],
         [ 0.6079, -0.4100,  0.4445,  ...,  0.3819, -0.7274,  2.0149],
         [ 3.1911, -0.5620, -0.5527,  ...,  0.9146, -1.6009,  2.7173],
         ...,
         [-1.4275,  1.3367, -1.4724,  ...,  1.5824,  0.0096, -1.4442],
         [ 1.4723, -1.2113,  0.9654,  ...,  0.9535, -2.0206,  2.0911],
         [-0.6311,  0.6034,  2.2262,  ...,  0.4331, -0.4317,  1.7093]],

        [[ 1.3927,  0.2743, -1.6030,  ...,  1.6879, -0.7731, -1.8428],
         [ 0.4260, -1.3306,  0.1924,  ...,  0.8357, -0.1475,  1.2991],
         [ 2.9368, -0.8859, -0.3223,  ...,  0.7163, -0.1594,  2.3750],
         ...,
         [-0.7528,  1.6444, -1.6862,  ...,  0.8677, -0.0069, -1.7844],
         [ 0.8316, -0.4052,  0.9214,  ...,  0.1002, -2.4656,  1.2147],
         [-0.7924,  0.2088,  1.5187,  ..., -0.0286, -0.2137,  1.0104]],

        [[ 0.4870, -0.1442, -1.6884,  ...,  0.9367, -0.8742, -2.0699],
         [ 0.9705, 